# ServiceMonitor for Azure Managed Prometheus
# Scrapes vLLM metrics from KAITO workspace

apiVersion: azmonitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: workspace-phi-4-mini-instruct-monitor
  namespace: default
spec:
  selector:
    matchLabels:
      kaito.sh/workspace: workspace-phi-4-mini-instruct
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scheme: http
