# KAITO Workspace for Phi-4-Mini-Instruct
# GPU: Standard_NV36ads_A10_v5 (1x A10 GPU, 24GB VRAM)
# Note: KAITO only supports NV36ads and NV72ads from the A10 family
# Uses custom ConfigMap (phi4-inference-config) to reduce max_model_len

apiVersion: kaito.sh/v1beta1
kind: Workspace
metadata:
  name: workspace-phi-4-mini-instruct
  namespace: default
resource:
  instanceType: "Standard_NV36ads_A10_v5"
  labelSelector:
    matchLabels:
      apps: phi-4-mini-instruct
inference:
  preset:
    name: phi-4-mini-instruct
  config: phi4-inference-config
